version: '3.8'

services:
  nuannuan_photo:
    image: nuannuan_photo:latest
    container_name: nuannuan_photo
    restart: always
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "18081:8081"
      - "13123:3000"
    volumes:
      - /mnt/sata2-1/nas_data/暖暖相册:/app/observer/public/images
      - /mnt/sata2-1/nas_data/暖暖相册:/app/server/public/images
      - /mnt/sata2-1/nas_data/暖暖相册:/app/web/dist/images
      - /mnt/sata2-1/nas_data/相册缩略图:/app/observer/public/thumbnails
      - /mnt/sata2-1/nas_data/相册缩略图:/app/server/public/thumbnails
      - /mnt/sata2-1/nas_data/相册缩略图:/app/web/dist/thumbnails